stages:
  prepare_data:
    cmd: python3 src/stage_01_prepare_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_01_prepare_data.py
      - data/data.xml
      - src/utils/all_utils.py
      - src/utils/data_management.py
      - config/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv

  featurize:
    cmd: python3 src/stage_02_featurization.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_featurization.py
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv
      - src/utils/all_utils.py
      - src/utils/featurize.py
      - config/config.yaml
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl
 
  train:
    cmd: python3 src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/features/train.pkl
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python3 src/stage_04_evaluate.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - artifacts/features/test.pkl
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  run_plots_command:
    cmd: dvc plots diff