stages:
  prepare_data:
    cmd: python3 src/stage_01_prepare_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_01_prepare_data.py
      - data/data.xml
      - src/utils/all_utils.py
      - src/utils/data_management.py
      - config/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv

 