name: train_NLP_DVC_usecase

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: cml_run
        env: 
          repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          # Your ML workflow commands
          pip3 install -- upgrade pip
          pip3 install -r requirements.txt

          dvc repro -v ## v means verbose output

          echo "# Reports" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md

          cml-send-comment report.md   

