name: train_NLP_DVC_usecase

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: "Deploy runner in EC2"
        shell: bash
        env: 
          REPO_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=t2.micro \
          --labels=cml-runner 
        


  model-training:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: docker://iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: "Train my model"
        env: 
          repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          # Your ML workflow commands
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

          dvc repro -v ## v means verbose output

          echo "# Reports" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md

          cml-send-comment report.md   

